language: objective-c
before_install:
    - cd `brew --prefix` && git fetch origin && git reset --hard origin/master && cd $TRAVIS_BUILD_DIR
    - brew update
    - brew install xctool --HEAD
    - bundle install
    - mkdir -p "RestKit.xcodeproj/xcshareddata/xcschemes" && cp Tests/Schemes/*.xcscheme "RestKit.xcodeproj/xcshareddata/xcschemes/"
script:
    - rake server:start
    - rake test
